#config_version=5

mode:
    start_events: start_mode_5
    stop_events: end_mode_5
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300

event_player:
 s_left_loop_made_active{current_player.mode_shot_enabled == 1}:
   - m5calculate
 right_loop_hit{current_player.mode_shot_enabled == 1}:
   - m5calculate
 mglobalcalculate: m5calculate



variable_player:
  m5calculate:
    score: current_player.m5value
    m5shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m5shotremaining:
      int: (4 - current_player.m5shotmade)
      action: set
    modetotal: current_player.m5value
    modeshotremaining:
      int: (current_player.m5shotremaining)
      action: set
  player_m5entrynumber{current_player.m5entrynumber < 4}:
    entry_modification:
      action: set
      float: (5 - current_player.m5entrynumber) / 4
  player_m5entrynumber{current_player.m5entrynumber >= 4}:
    entry_modification:
      action: set
      float: 1 / 4
  mode_mode_5_started:
    m5entrynumber:
      int: 1
      action: add
    modeentrynumber:
      int: current_player.m5entrynumber
      action: set
    m5value:
      int: 30000000 * current_player.entry_modification
      action: set
  player_entry_modification:
    m5value: 
      int: 30000000 * current_player.entry_modification
      action: set

show_player:
  m5calculate:
    sh_mode_5_shot_made:
      loops: 0