#config_version=5

mode:
  start_events: ball_starting
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 120

mode_settings:
  selectable_items: Skill1, Skill2, Skill3
  select_item_events: s_plunger_button
  next_item_events: s_right_flipper
  previous_item_events: s_left_flipper

slide_player:
  carousel_Skill1_highlighted: select_Skill1
  carousel_Skill2_highlighted: select_Skill2
  carousel_Skill3_highlighted: select_Skill3

slides:
  select_Skill1:
    widgets:
    - type: text
      text: Skill1
      font_size: 10
      color: yellow
  select_Skill2:
    widgets:
    - type: text
      text: Skill2
      font_size: 10
      color: yellow
  select_Skill3:
    widgets:
    - type: text
      text: Skill3
      font_size: 10
      color: yellow
