#config_version=5

mode:
  start_events: ball_started
  priority: 150

slides:
  prelaunch_slide: []

slide_player:
  mode_skill_shot_started:
    prelaunch_slide:
      priority: 120


achievements:
  skillshot_1:
    events_when_started: award_skillshot_1
    events_when_selected: skillshot_1_selected
  skillshot_2:
    events_when_started: award_skillshot_2
    events_when_selected: skillshot_2_selected
    enable_events: skillshot_1_selected
  skillshot_3:
    events_when_started: award_skillshot_3
    events_when_selected: skillshot_3_selected
    enable_events: skillshot_1_selected
  skillshot_4:
    events_when_started: award_skillshot_4
    events_when_selected: skillshot_4_selected
    enable_events: skillshot_1_selected
  skillshot_5:
    events_when_started: award_skillshot_5
    events_when_selected: skillshot_5_selected
    enable_events: skillshot_1_selected
  skillshot_6:
    events_when_started: award_skillshot_4
    events_when_selected: skillshot_4_selected
    enable_events: skillshot_1_selected
  skillshot_7:
    events_when_started: award_skillshot_3
    events_when_selected: skillshot_3_selected
    enable_events: skillshot_1_selected
  skillshot_8:
    events_when_started: award_skillshot_2
    events_when_selected: skillshot_2_selected
    enable_events: skillshot_1_selected

achievement_groups:
  skillshots:
    achievements: skillshot_1, skillshot_2, skillshot_3, skillshot_4, skillshot_5, skillshot_6, skillshot_7, skillshot_8
    auto_select: true
    #rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active, s_left_flipper_active
    allow_selection_change_while_disabled: no
    enable_while_no_achievement_started: no
    start_selected_events: start_mode
    enable_events: mode_skill_shot_started
    #disable_events: stop_mode_select

widget_player:
  skillshot_1_selected:
    skill_shot_select_widget_1:
      slide: prelaunch_slide
      action: add
    skill_shot_select_widget_2:
      action: remove
    skill_shot_select_widget_3:
      action: remove
    skill_shot_select_widget_4:
      action: remove
    skill_shot_select_widget_5:
      action: remove
  skillshot_2_selected:
    skill_shot_select_widget_2:
      slide: prelaunch_slide
      action: add
    skill_shot_select_widget_1:
      action: remove
    skill_shot_select_widget_3:
      action: remove
    skill_shot_select_widget_4:
      action: remove
    skill_shot_select_widget_5:
      action: remove
  skillshot_3_selected:
    skill_shot_select_widget_3:
      slide: prelaunch_slide
      action: add
    skill_shot_select_widget_1:
      action: remove
    skill_shot_select_widget_2:
      action: remove
    skill_shot_select_widget_4:
      action: remove
    skill_shot_select_widget_5:
      action: remove
  skillshot_4_selected:
    skill_shot_select_widget_4:
      slide: prelaunch_slide
      action: add
    skill_shot_select_widget_1:
      action: remove
    skill_shot_select_widget_2:
      action: remove
    skill_shot_select_widget_3:
      action: remove
    skill_shot_select_widget_5:
      action: remove
  skillshot_5_selected:
    skill_shot_select_widget_5:
      slide: prelaunch_slide
      action: add
    skill_shot_select_widget_1:
      action: remove
    skill_shot_select_widget_2:
      action: remove
    skill_shot_select_widget_3:
      action: remove
    skill_shot_select_widget_4:
      action: remove

  slide_prelaunch_slide_active{current_player.number == 1}:
    skillshot_up_selected_player_1_widget:
      slide: prelaunch_slide
      action: add
    skillshot_up_player_2_widget:
      slide: prelaunch_slide
      action: add
    skillshot_up_player_3_widget:
      slide: prelaunch_slide
      action: add
    skillshot_up_player_4_widget:
      slide: prelaunch_slide
      action: add


  slide_prelaunch_slide_active{current_player.number == 2}:
    skillshot_up_selected_player_2_widget:
      slide: prelaunch_slide
      action: add
    skillshot_up_player_1_widget:
      slide: prelaunch_slide
      action: add
    skillshot_up_player_3_widget:
      slide: prelaunch_slide
      action: add
    skillshot_up_player_4_widget:
      slide: prelaunch_slide
      action: add


  slide_prelaunch_slide_active{current_player.number == 3}:
    skillshot_down_selected_player_3_widget:
      slide: prelaunch_slide
      action: add
    skillshot_down_player_1_widget:
      slide: prelaunch_slide
      action: add
    skillshot_down_player_2_widget:
      slide: prelaunch_slide
      action: add
    skillshot_down_player_4_widget:
      slide: prelaunch_slide
      action: add


  slide_prelaunch_slide_active{current_player.number == 4}:
    skillshot_down_selected_player_4_widget:
      slide: prelaunch_slide
      action: add
    skillshot_down_player_1_widget:
      slide: prelaunch_slide
      action: add
    skillshot_down_player_2_widget:
      slide: prelaunch_slide
      action: add
    skillshot_down_player_3_widget:
      slide: prelaunch_slide
      action: add


  player_added{num==2}:
    skillshot_up_player_2_widget:
      slide: prelaunch_slide
      action: add
  player_added{num==3}:
    skillshot_up_player_3_widget:
      slide: prelaunch_slide
      action: add
  player_added{num==4}:
    skillshot_up_player_4_widget:
      slide: prelaunch_slide
      action: add




widgets:
  skill_shot_select_widget_1:
    - type: image
      image: skillshot_1
      x: middle
      y: middle
  skill_shot_select_widget_2:
    - type: image
      image: skillshot_2
      x: middle
      y: middle
  skill_shot_select_widget_3:
    - type: image
      image: skillshot_3
      x: middle
      y: middle
  skill_shot_select_widget_4:
    - type: image
      image: skillshot_4
      x: middle
      y: middle
  skill_shot_select_widget_5:
    - type: image
      image: skillshot_5
      x: middle
      y: middle


  skillshot_up_selected_player_1_widget:
    - type: text
      text: (player1|score)
      style: medium
      anchor_x: left
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: left+1
      y: top-1
      z: 105
      min_digits: 2
      number_grouping: true
      animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.4s
              easing: out_expo
              repeat: true

  skillshot_up_selected_player_2_widget:
    - type: text
      text: (player2|score)
      style: medium
      anchor_x: right
      anchor_y: top
      round_anchor_x: right
      round_anchor_y: top
      x: right
      y: top-1
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_up_player_1_widget:
    - type: text
      text: (player1|score)
      style: small
      anchor_x: left
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: left+1
      y: top-9
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_up_player_2_widget:
    - type: text
      text: (player2|score)
      style: small
      anchor_x: right
      anchor_y: top
      round_anchor_x: right
      round_anchor_y: top
      x: right
      y: top-9
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_up_player_3_widget:
    - type: text
      text: (player3|score)
      style: small
      anchor_x: left
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: left+1
      y: top-15
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_up_player_4_widget:
    - type: text
      text: (player4|score)
      style: small
      anchor_x: right
      anchor_y: top
      round_anchor_x: right
      round_anchor_y: top
      x: right
      y: top-15
      z: 105
      min_digits: 2
      number_grouping: true



  skillshot_down_selected_player_3_widget:
    - type: text
      text: (player3|score)
      style: medium
      anchor_x: left
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: left+1
      y: top-13
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_down_selected_player_4_widget:
    - type: text
      text: (player4|score)
      style: medium
      anchor_x: right
      anchor_y: top
      round_anchor_x: right
      round_anchor_y: top
      x: right
      y: top-13
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_down_player_1_widget:
    - type: text
      text: (player1|score)
      style: small
      anchor_x: left
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: left+1
      y: top-1
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_down_player_2_widget:
    - type: text
      text: (player2|score)
      style: small
      anchor_x: right
      anchor_y: top
      round_anchor_x: right
      round_anchor_y: top
      x: right
      y: top-1
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_down_player_3_widget:
    - type: text
      text: (player3|score)
      style: small
      anchor_x: left
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: left+1
      y: top-7
      z: 105
      min_digits: 2
      number_grouping: true

  skillshot_down_player_4_widget:
    - type: text
      text: (player4|score)
      style: small
      anchor_x: right
      anchor_y: top
      round_anchor_x: right
      round_anchor_y: top
      x: right
      y: top-7
      z: 105
      min_digits: 2
      number_grouping: true
