#config_version=5

mode:
    start_events: start_mode_6
    stop_events: end_mode_6
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300

event_player:
 sw_dmg_target{current_player.mode_shot_enabled == 1}: m6calculate
 mglobalcalculate: m6calculate

variable_player:
  m6calculate:
    score: m6value
    m6shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    modetotal: m6value
    m6shotremaining:
      int: (4 - current_player.m6shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m6shotremaining)
      action: set
  player_m6entrynumber{current_player.m6entrynumber < 4}:
    entry_modification:
      action: set
      float: (5 - current_player.m6entrynumber) / 4
  player_m6entrynumber{current_player.m6entrynumber >= 4}:
    entry_modification:
      action: set
      float: 1 / 4
  mode_mode_6_started:
    m6entrynumber:
      int: 1
      action: add
    m6value: 
      int: 25000000 * current_player.entry_modification
      action: set
  player_entry_modification:
    m6value: 
      int: 25000000 * current_player.entry_modification
      action: set

show_player:
  m6calculate:
    sh_mode_6_shot_made:
      loops: 0