#config_version=5

mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true

high_score:
  _overwrite: True
  enter_initials_timeout: 60
  award_slide_display_time: 4s

  # define your high score categories and the awards
  categories: !!omap
  - score:
      - GRAND ADMIRAL
      - ADMIRAL 1
      - ADMIRAL 2
      - ADMIRAL 3
      - ADMIRAL 4

  # set the defaults
  defaults:
    score:
      - SBA: 1000000000
      - OCP: 900000000
      - AND: 800000000
      - W G: 700000000
      - WOW: 600000000

# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: True
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display

slides:
  _overwrite: True
  high_score_enter_initials:
  - type: text
    style: small
    text: PLAYER (player_num)
    color: ffff00
    anchor_x: center
    anchor_y: top
    round_anchor_x: left
    round_anchor_y: top
    x: center
    y: top-1

  - type: text
    style: medium
    text: (award)
    color: f0f0f0
    #bold: true
    x: center-0.5
    y: top-10
    round_anchor_x: left
    round_anchor_y: top

  - type: text_input
    initial_char: A
    dynamic_x: false
    key: high_score
    style: small
    max_chars: 3
    anchor_y: bottom
    x: center
    y: bottom+2
    round_anchor_x: left
    round_anchor_y: top
    shift_left_event: s_left_flipper_active
    shift_right_event: s_right_flipper_active
    select_event: s_start_active
    color: ff0000

  - type: text
    style: small
    text: '<       >'
    anchor_y: bottom
    x: center
    y: bottom+2
    round_anchor_x: left
    round_anchor_y: top
    color: ff0000


  - type: text
    text: ''
    key: high_score
    font_size: 10
    style: big
    anchor_x: center
    anchor_y: center
    x: center
    y: center-3
    color: 00FF00
    round_anchor_x: left
    round_anchor_y: top
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.3s
        easing: in_out_quint
      - property: opacity
        value: 0
        duration: 0.3s
        repeat: true
        easing: in_out_quint

  high_score_award_display:
  - type: text
    text: (player_name)
    font_size: 13
    anchor_x: left
    anchor_y: bottom
    x: left+2
    y: bottom
    round_anchor_x: left
    round_anchor_y: top
    bold: true
    color: 00ff00
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.05s
      - property: opacity
        value: 0
        duration: 0.05s
        repeat: true
  - type: text
    text: (award)
    font_size: 15
    anchor_x: center
    anchor_y: top
    x: center
    y: top
    round_anchor_x: left
    round_anchor_y: top
    bold: true
    color: 0000ff
  - type: text
    text: (value)
    font_size: 13
    anchor_x: right
    anchor_y: bottom
    x: right-2
    y: bottom
    round_anchor_x: left
    round_anchor_y: top
    bold: true
    color: 4040FF
    number_grouping: true
    min_digits: 2