#config_version=5
mode:
    start_events: ball_starting
    priority: 100

variable_player:
    sw_dmg_target{current_player.DMGValue != 200000000}:
        DMGValue:
          action: add
          int: 10000000
    ball_started:
        DMGValue:
          action: set
          int: 120000000

slide_player:
  sw_dmg_target{current_player.DMGValue != 200000000}:
    dmg_value_increase_slide:
      action: play
      expire: 1s
  sw_dmg_target{current_player.DMGValue == 200000000}:
    dmg_value_maxed_slide:
      action: play
      expire: 1s

event_player:
    s_dmg_1_active:
        - drop_target_knockdown
        - drop_target_reset


slides:
    dmg_value_maxed_slide:
      - type: rectangle
        x: 1
        y: top-1
        z: 115
        anchor_y: top
        anchor_x: left
        width: 126
        height: 30
        opacity: 1
        color: black
      - type: rectangle
        x: 0
        y: top
        z: 110
        anchor_y: top
        anchor_x: left
        width: 128
        height: 32
        color: white
      - type: text
        text: DAMAGE VALUE
        x: 64
        y: top-5
        z: 120
        style: medium
        round_anchor_x: left
        round_anchor_y: top
        color: FF0000
      - type: text
        text: MAXED
        x: 64
        y: top-13
        z: 120
        style: medium
        round_anchor_x: left
        round_anchor_y: top
        color: 00FF00
      - type: text
        text: VALUE = (DMGValue)
        x: 64
        y: bottom+9
        z: 120
        style: big
        round_anchor_x: left
        round_anchor_y: top
        number_grouping: true
        color: 00FFFF
    dmg_value_increase_slide:
      - type: rectangle
        x: 1
        y: top-1
        z: 115
        anchor_y: top
        anchor_x: left
        width: 126
        height: 30
        opacity: 1
        color: black
      - type: rectangle
        x: 0
        y: top
        z: 110
        anchor_y: top
        anchor_x: left
        width: 128
        height: 32
        color: white
      - type: text
        text: DAMAGE VALUE
        x: 64
        y: top-5
        z: 120
        style: medium
        round_anchor_x: left
        round_anchor_y: top
        color: FF0000
      - type: text
        text: INCREASED
        x: 64
        y: top-13
        z: 120
        style: medium
        round_anchor_x: left
        round_anchor_y: top
        color: FF0000
      - type: text
        text: VALUE = (DMGValue)
        x: 64
        y: bottom+9
        z: 120
        style: big
        round_anchor_x: left
        round_anchor_y: top
        number_grouping: true
        color: 00FFFF
    main_slide:
      - type: text
        text: (score)
        anchor_x: center
        anchor_y: bottom
        x: 64
        y: 1
        #font_size: 5
        min_digits: 2
        z: 120
        style: small
        number_grouping: true
      - type: text
        text: PLAYER (number)
        y: 0
        x: 0
        font_size: 8
        anchor_x: left
        anchor_y: bottom
        color: blue
      - type: text
        text: BALL (ball)
        y: 0
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 8
        color: green

#slide_player:
#  mode_base_started: main_slide
#  main_state: main_slide
#  main_state_stopped:
#    main_slide:
#        action: remove


