#config_version=5

mode:
    start_events: ball_started
    priority: 100

timers:
  mode_countdown:
    start_value: 31
    end_value: 0
    direction: down
    start_running: false
    bcp: true
    control_events:
      - event: mode_countdown_run_disabled
        action: stop
      - event: mode_countdown_run_enabled
        action: start
      - event: mode_will_enabled
        action: reset
      - event: total_mode_timer_stop
        action: stop
      - event: total_mode_timer_reset
        action: reset
  mode_freeze:
    start_value: 16
    end_value: 0
    start_running: false
    direction: down
    control_events:
      - event: mode_freeze_run_disabled
        action: stop
      - event: mode_freeze_run_enabled
        action: start
      - event: mode_enabled
        action: reset
      - event: total_mode_timer_stop
        action: stop
      - event: total_mode_timer_reset
        action: reset
  mode_countdown_delay:
    start_value: 2
    end_value: 0
    start_running: false
    direction: down
    control_events:
      - event: mode_timer_quick_stop
        action: stop
      - event: mode_timer_quick_start
        action: restart
      - event: start_delay
        action: restart
      - event: total_mode_timer_stop
        action: stop
      - event: total_mode_timer_reset
        action: reset
  mode_overtime:
    start_value: 5
    end_value: 0
    start_running: false
    direction: down
    control_events:
      - event: mode_overtime_run_enabled
        action: start
      - event: mode_overtime_run_disabled
        action: stop
      - event: mode_overtime_reset
        action: reset
      - event: total_mode_timer_stop
        action: stop
      - event: total_mode_timer_reset
        action: reset
  mode_finish:
    start_value: 2
    end_value: 0
    start_running: false
    direction: down
    control_events:
      - event: mode_finish_timer_restart
        action: restart

queue_relay_player:
  mode_timer_quick_pause_starting:
    post: mode_timer_quick_stop
    wait_for: s_main_hole_inactive

queue_event_player:
  mode_timer_quick_pause_start:
    queue_event: mode_timer_quick_pause_starting
    events_when_finished: mode_timer_quick_start

event_player:
  more_time: mode_timer_quick_pause_start
  s_main_hole_active:
    - mode_timer_pause_event
    - mode_timer_quick_pause_start
  s_main_hole_inactive: mode_timer_pause_event
  sw_bumper_hit: mode_timer_pause_event


state_machines:
  mode_timer_state:
    starting_state: mode_timer_disabled
    states:
      mode_countdown_run:
        events_when_started: mode_countdown_run_enabled
        events_when_stopped: mode_countdown_run_disabled
      mode_countdown_pause:
        events_when_started: start_delay
        events_when_stopped: stop_delay
      mode_freeze_run:
        events_when_started: mode_freeze_run_enabled
        events_when_stopped: mode_freeze_run_disabled
      mode_freeze_pause:
        events_when_started: start_delay
        events_when_stopped: stop_delay
      mode_overtime_run:
        events_when_started: mode_overtime_run_enabled
        events_when_stopped: mode_overtime_run_disabled
      mode_overtime_pause:
        events_when_started: start_delay
        events_when_stopped: stop_delay
      mode_overtime_freeze_run:
        events_when_started: mode_overtime_freeze_run_enabled
        events_when_stopped: mode_overtime_freeze_run_disabled
      mode_overtime_freeze_pause:
        events_when_started: start_delay
        events_when_stopped: stop_delay
      mode_timer_disabled:
        label: Start state
        events_when_started: mode_timer_disable
        events_when_stopped: mode_timer_enabled
    transitions:
      - source: mode_countdown_run
        target: mode_countdown_pause
        events: mode_timer_pause_event
      - source: mode_countdown_pause
        target: mode_countdown_run
        events: timer_mode_countdown_delay_complete
      - source: mode_freeze_run
        target: mode_freeze_pause
        events: mode_timer_pause_event
      - source: mode_freeze_pause
        target: mode_freeze_run
        events: timer_mode_countdown_delay_complete
      - source: mode_overtime_run
        target: mode_overtime_pause
        events: mode_timer_pause_event
      - source: mode_overtime_pause
        target: mode_overtime_run
        events: timer_mode_countdown_delay_complete
      - source: mode_overtime_freeze_run
        target: mode_overtime_freeze_pause
        events: mode_timer_pause_event
      - source: mode_overtime_freeze_pause
        target: mode_overtime_freeze_run
        events: timer_mode_countdown_delay_complete
                                                      #INNETŐL KÜLSŐ VÁLTÁSOK, NEM CSAK RUN/STOP KAPCSOLAT
      - source: mode_countdown_pause
        target: mode_freeze_pause
        events: more_time
      - source: mode_freeze_run
        target: mode_countdown_run
        events: timer_mode_freeze_complete
      - source: mode_countdown_run
        target: mode_overtime_run
        events: timer_mode_countdown_complete
                                                      #MODE OVERTIME ÉS FREEZE KAPCSOLAT
      - source: mode_overtime_pause
        target: mode_overtime_freeze_pause
        events: more_time
      - source: mode_overtime_freeze_run
        target: mode_overtime_run
        events: timer_mode_freeze_complete
                                                      #MODE DISABLED KAPCSOLAT
      - source: mode_timer_disabled
        target: mode_freeze_pause
        events: more_time
      - source: mode_timer_disabled
        target: mode_countdown_pause
        events: start_mode_countdown
      - source: mode_overtime_run
        target: mode_timer_disabled
        events: timer_mode_overtime_complete
      - source: mode_countdown_run, mode_countdown_pause, mode_freeze_run, mode_freeze_pause, mode_overtime_run, mode_overtime_pause, mode_overtime_freeze_run, mode_overtime_freeze_pause
        target: mode_timer_disabled
        events: mode_state_machine_reset
