#config_version=5

mode:
    start_events: ball_started
    priority: 100

timers:
  mode_countdown:
    start_value: 30
    end_value: 0
    direction: down
    start_running: false
    bcp: true
    control_events:
      - event: pause_countdown
        action: stop
      - event: start_countdown
        action: start
      - event: mode_enabled
        action: restart
  mode_freeze:
    start_value: 0
    end_value: 0
    start_running: false
    direction: down
    control_events:
      - event: pause_frezee
        action: stop
      - event: start_frezee
        action: start
  mode_countdown_delay:
    start_value: 2
    end_value: 0
    start_running: false
    direction: down
    control_events:
      - event: bumper_hit
        action: restart
      - event: s_main_hole_active
        action: stop
      - event: s_main_hole_inactive
        action: restart
  mode_overtime:
    start_value: 5
    end_value: 0
    start_running: false
    direction: down
    control_events:
      - event: timer_mode_countdown_delay_complete
        action: start

event_player:
  s_main_hole_inactive: mode_timer_pause_event
  sw_bumper_hit: mode_timer_pause_event

  """
  timer_mode_countdown_delay_started{current_player.frezee_started == 0}: pause_countdown
  timer_mode_countdown_delay_started{current_player.frezee_started == 1}: pause_frezee
  timer_mode_countdown_delay_stopped{current_player.frezee_started == 0}: pause_countdown
  timer_mode_countdown_delay_stopped{current_player.frezee_started == 1}: pause_frezee
  timer_mode_countdown_delay_complete{current_player.frezee_started == 0}: start_countdown
  timer_mode_countdown_delay_complete{current_player.frezee_started == 1}: start_frezee
  """

state_machines:
  mode_timer_state:
    starting_state: mode_timer_disabled
    states:
      mode_countdown_run:
        events_when_started: mode_countdown_run_enabled
        events_when_stopped: mode_countdown_run_disabled
      mode_countdown_pause:
        events_when_started: start_delay
        events_when_stopped: stop_delay
      mode_freeze_run:
        events_when_started: mode_freeze_run_enabled
        events_when_stopped: mode_freeze_run_disabled
      mode_freeze_pause:
        events_when_started: start_delay
        events_when_stopped: stop_delay
      mode_overtime_run:
        events_when_started: mode_overtime_run_enabled
        events_when_stopped: mode_overtime_run_disabled
      mode_overtime_pause:
        events_when_started: start_delay
        events_when_stopped: stop_delay
      mode_overtime_freeze_run:
        events_when_started: mode_overtime_freeze_run_enabled
        events_when_stopped: mode_overtime_freeze_run_disabled
      mode_overtime_freeze_pause:
        events_when_started: start_delay
        events_when_stopped: stop_delay
      mode_timer_disabled:
        label: Start state
        events_when_started: mode_timer_disable
        events_when_stopped: mode_timer_enabled
    transitions:
      - source: mode_countdown_run
        target: mode_countdown_pause
        events: mode_timer_pause_event
      - source: mode_countdown_pause
        target: mode_countdown_run
        events: timer_mode_countdown_delay_complete
      - source: mode_freeze_run
        target: mode_freeze_pause
        events: mode_timer_pause_event
      - source: mode_freeze_pause
        target: mode_freeze_run
        events: timer_mode_countdown_delay_complete
      - source: mode_overtime_run
        target: mode_overtime_pause
        events: mode_timer_pause_event
      - source: mode_overtime_pause
        target: mode_overtime_run
        events: timer_mode_countdown_delay_complete
      - source: mode_overtime_freeze_run
        target: mode_overtime_freeze_pause
        events: mode_timer_pause_event
      - source: mode_overtime_freeze_pause
        target: mode_overtime_freeze_run
        events: timer_mode_countdown_delay_complete
                                                      #INNETŐL KÜLSŐ VÁLTÁSOK, NEM CSAK RUN/STOP KAPCSOLAT
      - source: mode_countdown_pause
        target: mode_freeze_pause
        events: more_time
      - source: mode_freeze_run
        target: mode_countdown_run
        events: timer_mode_freeze_complete
      - source: mode_countdown_run
        target: mode_overtime_run
        events: timer_mode_countdown_complete
                                                      #MODE OVERTIME ÉS FREEZE KAPCSOLAT
      - source: mode_overtime_pause
        target: mode_overtime_freeze_pause
        events: more_time
      - source: mode_overtime_freeze_run
        target: mode_overtime_run
        events: timer_mode_freeze_complete
                                                      #MODE DISABLED KAPCSOLAT
      - source: mode_timer_disabled
        target: mode_freeze_pause
        events: more_time
      - source: mode_timer_disabled
        target: mode_countdown_pause
        events: start_mode_countdown
      - source: mode_overtime_run
        target: mode_timer_disabled
        events: timer_mode_overtime_complete
      - source: mode_countdown_run, mode_countdown_pause, mode_freeze_run, mode_freeze_pause, mode_overtime_run, mode_overtime_pause, mode_overtime_freeze_run, mode_overtime_freeze_pause
        target: mode_timer_disabled
        events: mode_state_machine_reset

"""
variable_player:
  timer_mode_frezee_started:
    frezee_started:
      action: set 
      int: 1
  timer_mode_frezee_complete:
    frezee_started:
      action: set 
      int: 0
"""