#config_version=5

mode:
    start_events: start_mode_8
    stop_events: end_mode_8
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300

event_player:
 s_left_ramp_made_active{current_player.mode_shot_enabled == 1}:
   - m8calculate
 s_right_ramp_made_active{current_player.mode_shot_enabled == 1}:
   - m8calculate
 mglobalcalculate: m8calculate

variable_player:
  m8calculate:
    score: m8value
    modetotal: m8value
    m8shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m8shotremaining:
      int: (4 - current_player.m8shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m8shotremaining)
      action: set
  player_m8entrynumber{current_player.m8entrynumber < 4}:
    entry_modification:
      action: set
      float: (5 - current_player.m8entrynumber) / 4
  player_m8entrynumber{current_player.m8entrynumber >= 4}:
    entry_modification:
      action: set
      float: 1 / 4
  mode_mode_8_started:
    m8entrynumber:
      int: 1
      action: add
    m8value: 
      int: 20000000 * current_player.entry_modification
      action: set
  player_entry_modification:
    m8value: 
      int: 20000000 * current_player.entry_modification
      action: set

show_player:
  m8calculate:
    sh_mode_8_shot_made:
      loops: 0