#config_version=5

mode:
    start_events: start_mode_7
    stop_events: end_mode_7
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300

event_player:
 s_torpedo_active{current_player.mode_shot_enabled == 1}:
  - m7calculate
 refresh_m7_widgets{current_player.m7shotmade == 1}:
  - m7_torpedo_1_active
 refresh_m7_widgets{current_player.m7shotmade == 2}:
  - m7_torpedo_2_active
  - m7_torpedo_1_instant
 refresh_m7_widgets{current_player.m7shotmade == 3}:
  - m7_torpedo_3_active
  - m7_torpedo_1_instant
  - m7_torpedo_2_instant
 refresh_m7_widgets{current_player.m7shotmade > 3}:
  - m7_torpedo_1_instant
  - m7_torpedo_2_instant
  - m7_torpedo_3_instant
 slide_mode_slide_active{current_player.m7shotmade == 3}:
  - show_m7_final_value
 player_DMGValue{current_player.m7shotmade < 3}:
  - show_m7_normal_value
 player_DMGValue{current_player.m7shotmade == 3}:
  - show_m7_final_value
 mglobalcalculate: m7calculate
 m7calculate{current_player.m7shotmade < 3}: m7calculate_normal
 m7calculate{current_player.m7shotmade == 3}: m7calculate_final
 player_entry_modification{current_player.m7shotmade < 3}:
  - show_m7_normal_value
 player_entry_modification{current_player.m7shotmade == 3}:
  - show_m7_final_value

variable_player:
  m7calculate_normal:
    m7value: 
      int: (current_player.DMGValue / 4) * current_player.entry_modification
      action: set
    score: current_player.m7value
    modetotal: current_player.m7value
    m7shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m7shotremaining:
      int: (4 - current_player.m7shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m1shotremaining)
      action: set

  m7calculate_final:
    m7value: 
      int: (current_player.DMGValue) * current_player.entry_modification
      action: set
    score: current_player.m7value
    modetotal: current_player.m7value
    m7shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m7shotremaining:
      int: (4 - current_player.m7shotmade) * current_player.entry_modification
      action: set
    modeshotremaining:
      int: (current_player.m7shotremaining)
      action: set

  show_m7_normal_value:
    m7value: 
      int: (current_player.DMGValue / 4) * current_player.entry_modification
      action: set

  show_m7_final_value:
    m7value: 
      int: (current_player.DMGValue) * current_player.entry_modification
      action: set

  player_m7entrynumber{current_player.m7entrynumber < 4}:
    entry_modification:
      action: set
      float: (5 - current_player.m7entrynumber) / 4
  player_m7entrynumber{current_player.m7entrynumber >= 4}:
    entry_modification:
      action: set
      float: 1 / 4
  mode_mode_7_started:
    m7entrynumber:
      int: 1
      action: add
    modeentrynumber:
      int: current_player.m7entrynumber
      action: set
    m7value: 
      int: (current_player.DMGValue / 4) * current_player.entry_modification
      action: set


show_player:
  m7calculate:
    sh_mode_7_shot_made:
      loops: 0
      priority: 400

slides:
    mode_7_shot_made_slide_1:
      - type: image
        image: cons_7_background
    mode_7_shot_made_slide_2:
      - type: text
        text: TORPEDO LOADED
        style: big
        anchor_y: top
        y: top-2
        z: 2
        round_anchor_x: left
        round_anchor_y: top
        number_grouping: true
        min_digits: 2
        color: 00FFFF
      - type: text
        text: (m7value)
        style: big
        anchor_y: bottom
        y: bottom+2
        z: 2
        round_anchor_x: left
        round_anchor_y: top
        number_grouping: true
        min_digits: 2
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true





widgets:
  m7_torpedo_1:
    - type: image
      image: cons_7_torp
      round_anchor_x: left
      round_anchor_y: top
      anchor_x: left
      anchor_y: bottom
      x: 13
      y: 1
      z: 101
      animations:
        m7_torpedo_1_active:
            - property: x
              value: 65
              duration: 1s
              easing: in_out_expo
        m7_torpedo_1_instant:
            - property: x
              value: 65
              duration: 0.001s
  m7_torpedo_2:
    - type: image
      image: cons_7_torp
      round_anchor_x: left
      round_anchor_y: top
      anchor_x: left
      anchor_y: bottom
      x: 13
      y: 11
      z: 101
      animations:
        m7_torpedo_2_active:
            - property: x
              value: 65
              duration: 1s
              easing: in_out_expo
        m7_torpedo_2_instant:
            - property: x
              value: 65
              duration: 0.001s
  m7_torpedo_3:
    - type: image
      image: cons_7_torp
      round_anchor_x: left
      round_anchor_y: top
      anchor_x: left
      anchor_y: bottom
      x: 13
      y: 21
      z: 101
      animations:
        m7_torpedo_3_active:
            - property: x
              value: 65
              duration: 1s
              easing: in_out_expo
        m7_torpedo_3_instant:
            - property: x
              value: 65
              duration: 0.001s
  m7_foreground:
    - type: image
      image: cons_7_foreground
      anchor_x: left
      x: 0
      z: 102

