#config_version=5

mode:
    start_events: start_mode_7
    stop_events: end_mode_7
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300

event_player:
 s_torpedo_active{current_player.mode_shot_enabled == 1}:
  - m7calculate
 s_torpedo_active{current_player.m7shotmade == 2}:
  - show_m7_final_value
 player_DMGValue{current_player.m7shotmade < 3}:
  - show_m7_normal_value
 player_DMGValue{current_player.m7shotmade == 3}:
  - show_m7_final_value

variable_player:
  m7calculate{current_player.m7shotmade < 4}:
    m7value: 
      int: (current_player.DMGValue / 4)
      action: set
    score: current_player.m7value
    modetotal: current_player.m7value
    m7shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m7shotremaining:
      int: (4 - current_player.m7shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m1shotremaining)
      action: set
  m7calculate{current_player.m7shotmade == 4}:
    m7value: 
      int: (current_player.DMGValue)
      action: set
    score: current_player.m7value
    modetotal: current_player.m7value
    m7shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m7shotremaining:
      int: (4 - current_player.m7shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m7shotremaining)
      action: set
  show_m7_normal_value:
    m7value: 
      int: (current_player.DMGValue / 4)
      action: set
  show_m7_final_value:
    m7value: 
      int: (current_player.DMGValue)
      action: set
  mode_mode_7_started:
    m7value: 
      int: (current_player.DMGValue / 4)
      action: set

show_player:
  m7calculate:
    sh_mode_7_shot_made:
      loops: 0