#config_version=5

mode:
    start_events: start_mode_9
    stop_events: end_mode_9
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300

event_player:
  s_drop_target_active{current_player.mode_shot_enabled == 1}:
    - m9calculate_choice
  s_drop_target_active{current_player.m9shotmade == 2}:
    - c_drop_target_knockdown
    - enable_citadel_magnet
  s_citadel_active{current_player.mode_shot_enabled == 1}:
    - m9calculate_choice
  player_DMGValue{current_player.m9shotmade < 3}:
    - show_m9_normal_value
  player_DMGValue{current_player.m9shotmade == 3}:
    - show_m9_final_value
  mglobalcalculate: m9calculate
  slide_mode_slide_active{current_player.m9shotmade == 3}:
    - show_m9_final_value
  m9calculate_choice{current_player.m9shotmade < 3}: m9calculate
  m9calculate_choice{current_player.m9shotmade == 3}: m9calculatefinal
  player_entry_modification{current_player.m9shotmade < 3}:
    - show_m9_normal_value
  player_entry_modification{current_player.m9shotmade == 3}:
    - show_m9_final_value

variable_player:
  m9calculate:
    m9value: 
      int: (current_player.DMGValue / 4) * current_player.entry_modification
      action: set
    score: current_player.m9value
    modetotal: current_player.m9value
    m9shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m9shotremaining:
      int: (4 - current_player.m9shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m9shotremaining)
      action: set

  m9calculatefinal:
    m9value:
      int: (current_player.DMGValue) * current_player.entry_modification
      action: set
    score: current_player.m9value
    modetotal: current_player.m9value
    m9shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m9shotremaining:
      int: (4 - current_player.m9shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m9shotremaining)
      action: set

  show_m9_normal_value:
    m9value: 
      int: (current_player.DMGValue / 4) * current_player.entry_modification
      action: set

  show_m9_final_value:
    m9value: 
      int: (current_player.DMGValue) * current_player.entry_modification
      action: set

  player_m9entrynumber{current_player.m9entrynumber < 4}:
    entry_modification:
      action: set
      float: (5 - current_player.m9entrynumber) / 4
  player_m9entrynumber{current_player.m9entrynumber >= 4}:
    entry_modification:
      action: set
      float: 1 / 4
  mode_mode_9_started:
    m9entrynumber:
      int: 1
      action: add
    m9_phase_1_active:
      int: 1
      action: set
    m9_phase_2_active:
      int: 0
      action: set
    m9value: 
      int: (current_player.DMGValue / 4) * current_player.entry_modification
      action: set



show_player:
  m9calculate:
    sh_mode_9_shot_made:
      loops: 0