#config_version=5

mode:
    start_events: start_mode_1
    stop_events: end_mode_1
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300

event_player:
  sw_take_dmg{current_player.mode_shot_enabled == 1}:
    - m1calculate


variable_player:
  m1calculate:
    m1value: 
      int: (current_player.DMGValue * current_player.ReceivedDMG / 200)
      action: set
    modetotal: current_player.m1value
    score: current_player.m1value
    m1shotmade:
      int: 1
      action: add
    mode_shot_made:
      int: 1
      action: add
    m1shotremaining:
      int: (4 - current_player.m1shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m1shotremaining)
      action: set
  player_DMGValue:
    m1value: 
      int: (current_player.DMGValue * current_player.ReceivedDMG / 200)
      action: set
  player_RecivedDMG:
    m1value: 
      int: (current_player.DMGValue * current_player.ReceivedDMG / 200)
      action: set
  mode_mode_1_started:
    m1value: 
      int: (current_player.DMGValue * current_player.ReceivedDMG / 200)
      action: set

show_player:
  m1calculate:
    sh_mode_1_shot_made:
      loops: 0