#config_version=5

mode:
    start_events: start_mode_1
    stop_events: end_mode_1
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300


event_player:
  m1calculate_pre{current_player.mode_shot_enabled == 1}:
    - m1calculate
  mglobalcalculate: m1calculate


variable_player:
  m1calculate:
    m1value: 
      int: (current_player.DMGValue * (current_player.ReceivedDMG + 1) / 200) * current_player.entry_modification
      action: set
    modetotal: current_player.m1value
    score: current_player.m1value
    m1shotmade:
      int: 1
      action: add
    mode_shot_made:
      int: 1
      action: add
    m1shotremaining:
      int: (4 - current_player.m1shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m1shotremaining)
      action: set
  player_DMGValue:
    m1value: 
      int: (current_player.DMGValue * (current_player.ReceivedDMG + 1) / 200) * current_player.entry_modification
      action: set
  player_RecivedDMG:
    m1value: 
      int: (current_player.DMGValue * (current_player.ReceivedDMG + 1) / 200) * current_player.entry_modification
      action: set
  player_m1entrynumber{current_player.m1entrynumber < 4}:
    entry_modification:
      action: set
      float: (5 - current_player.m1entrynumber) / 4
  player_m1entrynumber{current_player.m1entrynumber >= 4}:
    entry_modification:
      action: set
      float: 1 / 4
  mode_mode_1_started:
    m1entrynumber:
      int: 1
      action: add
    modeentrynumber:
      int: current_player.m1entrynumber
      action: set
    m1value: 
      int: (current_player.DMGValue * (current_player.ReceivedDMG + 1) / 200) * current_player.entry_modification
      action: set
  player_entry_modification:
    m1value: 
      int: (current_player.DMGValue * (current_player.ReceivedDMG + 1) / 200) * current_player.entry_modification
      action: set

show_player:
  m1calculate{current_player.m1shotmade == 0}:
    sh_mode_1_shot_made_1:
      loops: 0
  m1calculate{current_player.m1shotmade == 1}:
    sh_mode_1_shot_made_2:
      loops: 0
  m1calculate{current_player.m1shotmade == 2}:
    sh_mode_1_shot_made_3:
      loops: 0
  m1calculate{current_player.m1shotmade == 3}:
    sh_mode_1_shot_made_4:
      loops: 0

widgets:
  mode_1_shot_made_score_widget:
      - type: text
        text: (m1value)
        style: small
        anchor_y: bottom
        y: bottom+2
        z: 2
        round_anchor_x: left
        round_anchor_y: top
        number_grouping: true
        min_digits: 2
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true