#config_version=5

config:
  #Primary config files
  - primary/config_else_virtual.yaml
  - primary/config_hardware.yaml
  - primary/config_keys.yaml
  - primary/config_logic.yaml
  - primary/config_modes.yaml
  - primary/config_operator_settings.yaml
  - primary/config_sound_music.yaml
  - primary/config_values.yaml
  - primary/config_virtual_hardware.yaml

  #Support config files
  - support/config_support_mode_end.yaml
  - support/config_support_hc.yaml
  - support/config_support_capture.yaml
  - support/config_support_commander.yaml
  - support/config_support_dmg_con.yaml
  - support/config_support_status_report.yaml
