#config_version=5

mode:
    start_events: capture_state
    stop_events: capture_state_stopped
    priority: 100

timers:
  capture_timer:
    start_value: 5
    end_value: 0
    tick_interval: 1s
    direction: down
    start_running: false
    bcp: true
    control_events:
      - event: sw_switch_hit
        action: restart
      - event: stop_dmg_con_timer
        action: stop

variable_player:
  player_capture_hurryup_capture_timer_tick:
    capture_timer_number:
      int: device.timers.capture_timer.ticks
      action: set
  mode_capture_hurryup_started:
    capture_timer_number:
      action: set
      int: 5

slides:
  capturing_slide_6: []
  captured_slide: []

slide_player:
  mode_capture_hurryup_started:
    capturing_slide_6:
      action: play
  play_captured_slide:
    captured_slide:
      action: play
  remove_captured_slide:
    captured_slide:
      action: remove



show_player:
  slide_capturing_slide_6_active:
    sh_capturing_6:
      loops: 0
  slide_captured_slide_active:
    sh_captured:
      loops: 0

event_player:
  check_capturing_letter: check_capturing_letter_hurryup
  s_torpedo_active:
    - play_captured_slide
  slide_captured_slide_removed:
    - area_captured
    - deactivate_capture

widget_player:
  check_capturing_letter_hurryup:
    widget_a:
      action: remove
    widget_b:
      action: remove
    widget_c:
      action: remove
    widget_d:
      action: remove
    widget_e:
      action: remove
    widget_flag:
      action: remove
  check_capturing_letter_hurryup{device.counters.capture_global_counter.value == 6}:
    widget_a:
      action: add
      slide: capturing_slide_6
  check_capturing_letter_hurryup{device.counters.capture_global_counter.value == 5}:
    widget_b:
      action: add
      slide: capturing_slide_6
  check_capturing_letter_hurryup{device.counters.capture_global_counter.value == 4}:
    widget_c:
      action: add
      slide: capturing_slide_6
  check_capturing_letter_hurryup{device.counters.capture_global_counter.value == 3}:
    widget_d:
      action: add
      slide: capturing_slide_6
  check_capturing_letter_hurryup{device.counters.capture_global_counter.value == 2}:
    widget_e:
      action: add
      slide: capturing_slide_6
  check_capturing_letter_hurryup{device.counters.capture_global_counter.value == 1}:
    widget_flag:
      action: add
      slide: capturing_slide_6

  check_captured_letter{device.counters.capture_global_counter.value == 6 and device.counters.capture_global_counter.value != 1}:
    widget_a:
      action: add
      slide: captured_slide
  check_captured_letter{device.counters.capture_global_counter.value == 5 and device.counters.capture_global_counter.value != 1}:
    widget_b:
      action: add
      slide: captured_slide
  check_captured_letter{device.counters.capture_global_counter.value == 4 and device.counters.capture_global_counter.value != 1}:
    widget_c:
      action: add
      slide: captured_slide
  check_captured_letter{device.counters.capture_global_counter.value == 3 and device.counters.capture_global_counter.value != 1}:
    widget_d:
      action: add
      slide: captured_slide
  check_captured_letter{device.counters.capture_global_counter.value == 2 and device.counters.capture_global_counter.value != 1}:
    widget_e:
      action: add
      slide: captured_slide


  active_capturing_widget_6_1:
    capturing_6_widget_1:
      action: add
      slide: capturing_slide_6
  remove_capturing_widget_6_1:
    capturing_6_widget_1:
      action: remove
    widget_a:
      action: remove
    widget_b:
      action: remove
    widget_c:
      action: remove
    widget_d:
      action: remove
    widget_e:
      action: remove
    widget_flag:
      action: remove
  active_capturing_widget_6_2:
    capturing_6_widget_2:
      action: add
      slide: capturing_slide_6
    capture_counter_widget:
      action: add
      slide: capturing_slide_6

  active_captured_widget_1{device.counters.capture_global_counter.value == 1}:
    captured_base_widget_1:
      action: add
      slide: captured_slide
  active_captured_widget_1{device.counters.capture_global_counter.value != 1}:
    captured_widget_1:
      action: add
      slide: captured_slide
  remove_captured_widget_1:
    captured_widget_1:
      action: remove
    captured_base_widget_1:
      action: remove
  active_captured_widget_2{device.counters.capture_global_counter.value == 1}:
    captured_base_widget_2:
      action: add
      slide: captured_slide
  active_captured_widget_2{device.counters.capture_global_counter.value != 1}:
    captured_widget_2:
      action: add
      slide: captured_slide
  remove_captured_widget_2:
    captured_widget_2:
      action: remove
    captured_base_widget_2:
      action: remove

widgets:
  capture_counter_widget:
    - type: text
      text: (capture_timer_number)
      x: 17
      y: 16
      z: 150
      style: big
      round_anchor_x: left
      round_anchor_y: top
      font_size: 14
  captured_widget_1:
      - type: image
        image: captured
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: AREA CAPTURED
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: top-2
        z: 130
        style: big
        anchor_x: middle
        anchor_y: top
        color: 00FFFF
      - type: text
        text: CHOOSE CAPTURE
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: 16
        z: 130
        style: medium
        anchor_x: middle
        anchor_y: top
        color: FFFF00
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
      - type: text
        text: REWARD
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: bottom+2
        z: 130
        style: medium
        anchor_x: middle
        anchor_y: bottom
        color: FFFF00
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
  captured_widget_2:
      - type: image
        image: captured_still
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: AREA CAPTURED
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: top-2
        z: 130
        style: big
        anchor_x: middle
        anchor_y: top
        color: 00FFFF
      - type: text
        text: CHOOSE CAPTURE
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: 16
        z: 130
        style: medium
        anchor_x: middle
        anchor_y: top
        color: FFFF00
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
      - type: text
        text: REWARD
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: bottom+2
        z: 130
        style: medium
        anchor_x: middle
        anchor_y: bottom
        color: FFFF00
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
  captured_base_widget_1:
      - type: image
        image: captured_base
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: BASE CAPTURED
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: top-2
        z: 130
        style: big
        anchor_x: middle
        anchor_y: top
        color: 00FFFF
      - type: text
        text: AWARD ALL
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: 16
        z: 130
        style: medium
        anchor_x: middle
        anchor_y: top
        color: FFFF00
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
      - type: text
        text: CAPTURE REWARD
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: bottom+2
        z: 130
        style: medium
        anchor_x: middle
        anchor_y: bottom
        color: FFFF00
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
  captured_base_widget_2:
      - type: image
        image: captured_base_still
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: BASE CAPTURED
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: top-2
        z: 130
        style: big
        anchor_x: middle
        anchor_y: top
        color: 00FFFF
      - type: text
        text: AWARD ALL
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: 16
        z: 130
        style: medium
        anchor_x: middle
        anchor_y: top
        color: FFFF00
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
      - type: text
        text: CAPTURE REWARD
        round_anchor_x: left
        round_anchor_y: top
        x: 80
        y: bottom+2
        z: 130
        style: medium
        anchor_x: middle
        anchor_y: bottom
        color: FFFF00
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
