#config_version=5

show_player:
  slide_dmg_con_total_slide_active{current_player.m10_finished == 1}:
    sh_mode_10_completed:
      loops: 0
      priority: 600
  slide_dmg_con_total_slide_active{current_player.m10_finished == 0}:
    sh_mode_10_progress:
      loops: 0
      priority: 600

slides:
  dmg_con_total_slide: []

slide_player:
  mode_10_will_end:
    dmg_con_total_slide:
      priority: 600
  mode_completed_finished:
    dmg_con_total_slide:
      action: remove

widgets:
  end_mode_10_progress_transition:
      - type: image
        image: mode_10_progress
        x: 0
        y: 0
        z: 200
        loops: 0
        anchor_x: left
        anchor_y: bottom
        fps: 20
  end_mode_10_completed_transition:
      - type: image
        image: mode_10_completed
        x: 0
        y: 0
        z: 200
        loops: 0
        anchor_x: left
        anchor_y: bottom
        fps: 20
  end_mode_10_description_transition:
      - type: image
        image: mode_10_desc_rev
        x: 0
        y: 0
        z: 200
        loops: 0
        anchor_x: left
        anchor_y: bottom
        fps: 33
  end_mode_10_description:
      - type: image
        image: mode_10_desc_still
        x: 0
        y: 0
        z: 200
        anchor_x: left
        anchor_y: bottom
  end_mode_10_total:
      - type: image
        image: dmg_con_party_icon
        x: 112
        y: middle
        z: 150
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: TOTAL
        x: 48
        anchor_y: top
        number_grouping: true
        y: top-1
        z: 115
        color: 00FF00
        style: big
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: (dmg_con_total)
        x: 48
        z: 115
        anchor_y: top
        number_grouping: true
        y: top-12
        style: big
        round_anchor_x: left
        round_anchor_y: top
  end_mode_10_total_progress:
      - type: image
        image: dmg_con_party_icon
        x: 112
        y: middle
        z: 150
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: TOTAL
        x: 48
        anchor_y: top
        number_grouping: true
        y: top-1
        z: 115
        color: 00FF00
        style: big
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: (dmg_con_total)
        x: 48
        z: 115
        anchor_y: top
        number_grouping: true
        y: top-12
        style: big
        round_anchor_x: left
        round_anchor_y: top
  end_mode_10_progress:
      - type: image
        image: dmg_con_party_icon
        x: 16
        y: middle
        z: 150
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: DAMAGE CONTROL
        x: 80
        z: 105
        anchor_y: top
        y: top
        style: big
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: PARTY
        x: 80
        z: 105
        anchor_y: top
        y: top-11
        style: big
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: INCOMPLETE
        x: 80
        z: 105
        anchor_y: top
        y: top-22
        style: big
        color: FF0000
        round_anchor_x: left
        round_anchor_y: top
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true
  end_mode_10_completed:
      - type: text
        text: DAMAGE CONTROL
        x: 80
        anchor_y: top
        y: top
        z: 105
        style: big
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: PARTY
        x: 80
        z: 105
        anchor_y: top
        y: top-11
        style: big
        round_anchor_x: left
        round_anchor_y: top
      - type: image
        image: dmg_con_party_icon
        x: 16
        y: middle
        z: 150
        round_anchor_x: left
        round_anchor_y: top
      - type: text
        text: COMPLETED
        x: 81
        z: 105
        anchor_y: top
        y: top-22
        style: big
        color: 00FF00
        round_anchor_x: left
        round_anchor_y: top
        animations:
          add_to_slide:
            - property: opacity
              value: 0
              duration: 0.1s
              easing: in_out_expo
            - property: opacity
              timing: after_previous
              value: 1
              duration: 0.1s
              easing: in_out_expo
              repeat: true


widget_player:
  mode_10_end_completed_slide_add:
    end_mode_10_completed:
      slide: dmg_con_total_slide
      action: add
  mode_10_end_completed_slide_transition_add:
    end_mode_10_completed_transition:
      slide: dmg_con_total_slide
      action: add
  mode_10_end_completed_slide_remove:
    end_mode_10_completed:
      slide: dmg_con_total_slide
      action: remove
  mode_10_end_total_slide_add:
    end_mode_10_total:
      slide: dmg_con_total_slide
      action: add
  mode_10_end_completed_slide_transition_remove:
    end_mode_10_completed_transition:
      slide: dmg_con_total_slide
      action: remove
  mode_10_end_desc_slide_transition_add:
    end_mode_10_description_transition:
      slide: dmg_con_total_slide
      action: add
  mode_10_end_desc_slide_add:
    end_mode_10_description:
      slide: dmg_con_total_slide
      action: add
  mode_10_end_desc_slide_transition_remove:
    end_mode_10_description_transition:
      slide: dmg_con_total_slide
      action: remove
  mode_10_end_total_slide_remove:
    end_mode_10_total:
      slide: dmg_con_total_slide
      action: remove
  mode_10_end_desc_slide_remove:
    end_mode_10_description:
      slide: dmg_con_total_slide
      action: remove
  mode_10_end_progress_slide_add:
    end_mode_10_progress:
      slide: dmg_con_total_slide
      action: add
  mode_10_end_progress_slide_transition_add:
    end_mode_10_progress_transition:
      slide: dmg_con_total_slide
      action: add
  mode_10_end_progress_slide_remove:
    end_mode_10_progress:
      slide: dmg_con_total_slide
      action: remove
  mode_10_end_progress_slide_transition_remove:
    end_mode_10_progress_transition:
      slide: dmg_con_total_slide
      action: remove
  mode_10_end_total_progress_slide_add:
    end_mode_10_total_progress:
      slide: dmg_con_total_slide
      action: add
  mode_10_end_total_progress_slide_remove:
    end_mode_10_total_progress:
      slide: dmg_con_total_slide
      action: remove
