#config_version=5

state_machines:
  commander_1_state:
    starting_state: white
    states:
      white:
        events_when_started: commander_1_changed
      c_r:
        events_when_started: commander_1_changed
      c_b:
        events_when_started: commander_1_changed
      c_y:
        events_when_started: commander_1_changed
      c_g:
        events_when_started: commander_1_changed
      c_r_locked:
        events_when_started: commander_1_changed
      c_b_locked:
        events_when_started: commander_1_changed
      c_y_locked:
        events_when_started: commander_1_changed
      c_g_locked:
        events_when_started: commander_1_changed
      black:
        events_when_started: commander_1_changed
    transitions:
      - source: white
        target: c_y
        events: c_y
      - source: white
        target: c_g
        events: c_g
      - source: white
        target: c_b
        events: c_b
      - source: white
        target: c_r
        events: c_r
      - source: c_y
        target: black
        events: c_r, c_g, c_b, c_r_end, c_g_end, c_b_end
      - source: c_g
        target: black
        events: c_r, c_y, c_b, c_r_end, c_y_end, c_b_end
      - source: c_b
        target: black
        events: c_r, c_g, c_y, c_r_end, c_g_end, c_y_end
      - source: c_r
        target: black
        events: c_y, c_g, c_b, c_y_end, c_g_end, c_b_end
      - source: c_y
        target: c_y_locked
        events: c_y_end
      - source: c_g
        target: c_g_locked
        events: c_g_end
      - source: c_b
        target: c_b_locked
        events: c_b_end
      - source: c_r
        target: c_r_locked
        events: c_r_end