#config_version=5

slides:
  status_report_scores: []

slide_player:
  

widget_player:
  
  # First event, before additional players have a chance to enter
  game_started:
    sr_base_score_widget:
      slide: status_report_scores
    sr_base_level_widget:
      slide: status_report_scores
    sr_base_ball_widget:
      slide: status_report_scores

  # Player 2 has entered the game
  player_added{num==2}:
    sr_mp_score_widget:
      slide: status_report_scores
    sr_base_level_widget:
      slide: status_report_scores
    sr_base_ball_widget:
      slide: status_report_scores
    # Start with player1 name and player2 score
    sr_mp_name_widget_player_1:
      slide: status_report_scores
    sr_mp_score_widget_player_2:
      slide: status_report_scores


  # Player 3 has entered the game
  player_added{num==3}:
    sr_mp_score_widget_player_3:
      slide: status_report_scores
    # Remove the "Level" widget and place the player3 score


  # Player 4 has entered the game
  player_added{num==4}:
    sr_mp_score_widget_player_4:
      slide: status_report_scores
    # Remove the "Ball" widget and place the player4 score



  #{ ... base and multi-player widgets ...}

  # Player Turns: Swap scores -> names when turn starts, revert when turn ends
  player_turn_started{number==1}:
    sr_mp_score_widget_player_1:
      action: remove
    sr_mp_name_widget_player_1:
      slide: status_report_scores
  player_turn_ended{number==1}:
    sr_mp_score_widget_player_1:
      slide: status_report_scores
    sr_mp_name_widget_player_1:
      action: remove
  player_turn_started{number==2}:
    sr_mp_score_widget_player_2:
      action: remove
    sr_mp_name_widget_player_2:
      slide: status_report_scores
  player_turn_ended{number==2}:
    sr_mp_score_widget_player_2:
      slide: status_report_scores
    sr_mp_name_widget_player_2:
      action: remove
  player_turn_started{number==3}:
    sr_mp_score_widget_player_3:
      action: remove
    sr_mp_name_widget_player_3:
      slide: status_report_scores
  player_turn_ended{number==3}:
    sr_mp_score_widget_player_3:
      slide: status_report_scores
    sr_mp_name_widget_player_3:
      action: remove
  player_turn_started{number==4}:
    sr_mp_score_widget_player_4:
      action: remove
    sr_mp_name_widget_player_4:
      slide: status_report_scores
  player_turn_ended{number==4}:
    sr_mp_score_widget_player_4:
      slide: status_report_scores
    sr_mp_name_widget_player_4:
      action: remove


widgets:
  sr_base_score_widget:
    - type: text
      anchor_y: center
      anchor_x: center
      y: center
      x: center
      round_anchor_x: left
      round_anchor_y: top
      text: (score)
      style: big
      font_size: 14
      min_digits: 2
      number_grouping: true
  sr_base_level_widget:
    - type: text
      anchor_y: bottom
      anchor_x: right
      y: bottom+1
      x: right-1
      round_anchor_x: left
      round_anchor_y: top
      text: FREE PLAY
      style: small
  sr_base_ball_widget:
    - type: text
      anchor_y: bottom
      anchor_x: left
      y: bottom+1
      x: left+1
      round_anchor_x: left
      round_anchor_y: top
      text: BALL (ball)
      style: small


  sr_mp_score_widget:
    - type: text
      text: (score)
      style: medium
      round_anchor_x: left
      round_anchor_y: top
      min_digits: 2
      number_grouping: true
      anchor_y: top
      y: top-10

  # Player 1 score, for when they're not playing
  sr_mp_score_widget_player_1:
    - type: text
      text: (player1|score)
      style: small
      anchor_x: right
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: center-2
      y: top-2
      min_digits: 2
      number_grouping: true
  # Player 2 score, for when they're not playing
  sr_mp_score_widget_player_2:
    - type: text
      text: (player2|score)
      style: small
      anchor_x: right
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: right-2
      y: top-2
      min_digits: 2
      number_grouping: true

  # Player 1 custom variable, for when they are playing
  sr_mp_name_widget_player_1:
    - type: text
      text: (machine|last_career_player_1)
      style: small
      anchor_x: right
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: center-2
      y: top-2
      min_digits: 2
      number_grouping: true
  # Player 2 custom variable, for when they are playing
  sr_mp_name_widget_player_2:
    - type: text
      text: (machine|last_career_player_2)
      style: small
      anchor_x: right
      anchor_y: top
      round_anchor_x: left
      round_anchor_y: top
      x: right-2
      y: top-2
      min_digits: 2
      number_grouping: true

  #{ ... single and player_2 widgets .. }

  sr_mp_score_widget_player_3:
    - type: text
      text: (player3|score)
      style: small
      anchor_x: right
      anchor_y: bottom
      round_anchor_x: left
      round_anchor_y: top
      x: center-2
      y: bottom+7
      min_digits: 2
      number_grouping: true
  sr_mp_score_widget_player_4:
    - type: text
      text: (player4|score)
      style: small
      anchor_x: right
      anchor_y: bottom
      round_anchor_x: left
      round_anchor_y: top
      x: right-2
      y: bottom+7
      min_digits: 2
  sr_mp_name_widget_player_3:
    - type: text
      text: (machine|last_career_player_3)
      style: small
      anchor_x: right
      anchor_y: bottom
      round_anchor_x: left
      round_anchor_y: top
      x: center-2
      y: bottom+7
      min_digits: 2
  sr_mp_name_widget_player_4:
    - type: text
      text: (machine|last_career_player_4)
      style: small
      anchor_x: right
      anchor_y: bottom
      round_anchor_x: left
      round_anchor_y: top
      x: right-2
      y: bottom+7
      min_digits: 2