#config_version=6

show_player:
  has_match:
    sh_match:
      priority: 99
  no_match:
    sh_match:
      priority: 99

queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: match_end
    pass_args: true
  match_has_match:
    post: has_match
    wait_for: match_end
    pass_args: true


mode_settings:
  non_match_number_step: 10


sound_player:
  match_no_match:
    no_match_sound:
      action: play
  match_has_match:
    match_sound:
      action: play
