#config_version=5

hardware:
  #platform: smart_virtual
  rgb_dmd: pin2dmd


pin2dmd:
  debug: True           # uncomment this if you experience any issues and need debug output
  resolution: 128x32       # or 192x64 depending on your panel
  panel: rgb

rgb_dmds:
  default:  # your DMD
    brightness: 1      # adjust the brightness of your display if it is too bright
    fps: 30

drop_targets:
     citadel_drop_target:
         switch: s_drop_target
         reset_coil: c_drop_target_reset
         knockdown_coil: c_drop_target_knockdown
         reset_events: drop_target_reset
         knockdown_events: drop_target_knockdown
         disable_keep_up_events: disable_drop_target
         enable_keep_up_events: enable_drop_target

magnets:
  citadel_magnet:
    magnet_coil: c_citadel_magnet
    grab_switch: s_conning_tower
    enable_events: enable_citadel_magnet
    disable_events: disable_citadel_magnet
    reset_events: reset_citadel_magnet
    release_ball_events: citadel_relase

ball_devices:
  bd_trough:
    tags: trough, home, drain
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough_jam
    eject_coil: c_trough_eject
    entrance_count_delay: 300ms
    jam_switch: s_trough_jam
    eject_targets: bd_plunger
    debug: yes
  bd_plunger:
    ball_switches: s_plunger
    entrance_count_delay: 300ms
    eject_timeouts: 3s
    eject_coil: c_plunger
    player_controlled_eject_event: s_plunger_button_active
  bd_main_hole:
    ball_switches: s_main_hole
    eject_coil: c_scoop_eject
    eject_timeouts: 1s
  bd_hc_lock:
    entrance_count_delay: 500ms # Default: 500ms
    ball_switches: s_lock_1, s_lock_2, s_lock_3
    eject_coil: c_lock_eject
    eject_events: lock_eject_one_ball
    eject_all_events: game_ended
    eject_coil_enable_time:
    eject_timeouts: 3s
    exit_count_delay: 2s
    ball_missing_timeouts:

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper

  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper

  right_upper_flipper:
    main_coil: c_flipper_right_upper_main
    hold_coil: c_flipper_right_upper_hold
    activation_switch: s_right_flipper


autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  bumper_1:
    coil: c_bumper_1
    switch: s_bumper_1
  bumper_2:
    coil: c_bumper_2
    switch: s_bumper_2
  bumper_3:
    coil: c_bumper_3
    switch: s_bumper_3


switches:
  s_left_flipper:
    number: 0
    tags: left_flipper
  s_right_flipper:
    number: 1
    tags: right_flipper
  s_trough1:
    number: 2
  s_trough2:
    number: 3
  s_trough3:
    number: 4
  s_trough4:
    number: 5
  s_trough5:
    number: 6
  s_trough6:
    number: 7
  s_trough_jam:
    number: 8
  s_plunger:
    number: 9
    tags:
  s_start:
    number: 10
    tags: start
  s_right_inlane:
    number: 11
    tags: switch_hit
  s_right_outlane:
    number: 12
    tags: switch_hit
  s_left_inlane:
    number: 13
    tags: switch_hit
  s_left_mid_inlane:
    number: 14
    tags: switch_hit
  s_left_outlane:
    number: 15
    tags: switch_hit
  s_kickback:
    number: 16
    tags: switch_hit
  s_right_slingshot:
    number: 17
    tags: switch_hit
  s_left_slingshot:
    number: 18
    tags: switch_hit
  s_kickback_target_1:
    number: 19
    tags: switch_hit
  s_kickback_target_2:
    number: 20
    tags: switch_hit
  s_kickback_target_3:
    number: 21
    tags: switch_hit
  s_lock_1:
    number: 22
    tags: switch_hit
  s_lock_2:
    number: 23
    tags: switch_hit
  s_lock_3:
    number: 24
    tags: switch_hit
  s_dmg_1:
    number: 25
    tags: take_dmg, switch_hit, take_hc_dmg
  s_dmg_2:
    number: 26
    tags: take_dmg, switch_hit, take_hc_dmg
  s_dmg_3:
    number: 27
    tags: take_dmg, switch_hit, take_hc_dmg
  s_dmg_4:
    number: 28
    tags: take_dmg, switch_hit, take_hc_dmg
  s_dmg_5:
    number: 29
    tags: take_dmg, switch_hit, take_hc_dmg
  s_dmg_6:
    number: 30
    tags: take_dmg, switch_hit, take_hc_dmg
  s_dmg_7:
    number: 31
    tags: take_dmg, switch_hit, take_hc_dmg
  s_ricochet_1:
    number: 32
    tags: dmg_target, switch_hit, take_hc_dmg
  s_ricochet_2:
    number: 33
    tags: dmg_target, switch_hit, take_hc_dmg
  s_ricochet_3:
    number: 34
    tags: dmg_target, switch_hit, take_hc_dmg
  s_ricochet_4:
    number: 35
    tags: dmg_target, switch_hit, take_hc_dmg
  s_detonation:
    number: 36
    tags: switch_hit
  s_pen_1:
    number: 37
    tags: pen_target, switch_hit
  s_pen_2:
    number: 38
    tags: pen_target, switch_hit
  s_pen_3:
    number: 39
    tags: pen_target, switch_hit
  s_bumper_1:
    number: 43
    tags: bumper_hit, switch_hit
  s_bumper_2:
    number: 44
    tags: bumper_hit, switch_hit
  s_bumper_3:
    number: 45
    tags: bumper_hit, switch_hit
  s_torpedo:
    number: 46
    tags: switch_hit
  s_drop_target:
    number: 47
    tags: switch_hit
  s_conning_tower:
    number: 48
    tags: switch_hit
  s_detonation_lit:
    number: 49
    tags: switch_hit
  s_left_loop_pre:
    number: 50
    tags: switch_hit
  s_left_loop_made:
    number: 51
    tags: switch_hit
  s_left_ramp_pre:
    number: 52
    tags: switch_hit
  s_left_ramp_made:
    number: 53
    tags: capture, switch_hit
  s_side_ramp_pre:
    number: 54
    tags: switch_hit
  s_side_ramp_made:
    number: 55
    tags: switch_hit
  s_center_ramp:
    number: 56
    tags: switch_hit
  s_right_ramp_pre:
    number: 57
    tags: switch_hit
  s_right_ramp_made:
    number: 58
    tags: capture, switch_hit
  s_right_loop_made:
    number: 60
    tags: switch_hit
  s_main_hole:
    number: 61
    tags: switch_hit
  s_side_hole:
    number: 62
    tags: switch_hit
  s_right_loop_pre:
    number: 63
    tags: switch_hit
  s_citadel:
    number: 64
    tags: switch_hit
  s_plunger_button:
    number: 65
  s_torpedo_pre:
    number: 66
    tags: switch_hit
  s_action_button:
    number: 67

lights:
  l_shoot_again:
    number: 0
  l_kickback:
    number: 1
  l_a:
    number: 2
  l_b:
    number: 3
  l_c:
    number: 4
  l_d:
    number: 5
  l_e:
    number: 6
  l_destroyer:
    number: 7
  l_cruiser:
    number: 8
  l_battleship:
    number: 9
  l_carrier:
    number: 10
  l_kickback_1:
    number: 11
  l_kickback_2:
    number: 12
  l_kickback_3:
    number: 13
  l_medal_krakken:
    number: 14
  l_medal_witherer:
    number: 15
  l_medal_drednaught:
    number: 16
  l_medal_high_caliber:
    number: 17
  l_medal_confederate:
    number: 18
  l_mode_1:
    number: 19
  l_mode_2:
    number: 20
  l_mode_3:
    number: 21
  l_mode_4:
    number: 22
  l_mode_5:
    number: 23
  l_mode_6:
    number: 24
  l_mode_7:
    number: 25
  l_mode_8:
    number: 26
  l_mode_9:
    number: 27
  l_mode_final:
    number: 28
  l_damage_multiball:
    number: 29
  l_ricichet_1:
    number: 30
  l_ricichet_2:
    number: 31
  l_ricichet_3:
    number: 32
  l_ricichet_4:
    number: 33
  l_salvo:
    number: 35
  l_lock_lit_1:
    number: 36
  l_lock_lit_2:
    number: 37
  l_lock:
    number: 38
  l_detonation_lit:
    number: 39
  l_detonation:
    number: 40
  l_fire_2:
    number: 42
  l_double_strike_1:
    number: 43
  l_double_strike_2:
    number: 44
  l_double_strike_3:
    number: 45
  l_double_strike_4:
    number: 46
  l_double_strike_5:
    number: 47
  l_solo_warrior:
    number: 48
  l_left_loop_confederate:
    number: 49
  l_left_loop_jackpot:
    number: 50
  l_left_ramp_confederate:
    number: 51
  l_left_ramp_jackpot:
    number: 52
  l_super_jackpot:
    number: 53
  l_torpedo_confederate:
    number: 54
  l_torpedo_jackpot:
    number: 55
  l_citadel_confederate:
    number: 56
  l_citadel_jackpot:
    number: 57
  l_center_ramp_confederate:
    number: 58
  l_center_ramp_jackpot:
    number: 59
  l_right_ramp_confederate:
    number: 60
  l_right_ramp_jackpot:
    number: 61
  l_side_hole:
    number: 62
  l_mode_start_lit:
    number: 63
  l_container_lit:
    number: 64
  l_extra_ball:
    number: 65
  l_fire_1:
    number: 67
  l_citadel:
    number: 68
  l_fire_3:
    number: 69
  l_action_button:
    number: 70

coils:
  c_flipper_left_main:
    number: 0 
  c_flipper_left_hold:
    number: 1 
    allow_enable: true
  c_flipper_right_main:
    number: 2
  c_flipper_right_hold:
    number: 3
    allow_enable: true
  c_flipper_right_upper_main:
    number: 4
  c_flipper_right_upper_hold:
    number: 5
    allow_enable: true
  c_trough_eject:
    number: 6
    default_pulse_ms: 20
  c_plunger:
    number: 7
  c_kickback:
    number: 8
  c_left_slingshot:
    number: 9
  c_right_slingshot:
    number: 10
  c_lock_eject:
    number: 11
  c_side_ramp_diverter:
    number: 12
  c_left_loop_diverter:
    number: 13
  c_torpedo_peg:
    number: 14
  c_citadel_peg:
    number: 15
  c_citadel_magnet:
    number: 16
    default_pulse_ms: 100
    default_hold_power: 0.375
  c_drop_target_knockdown:
    file_log: full
    number: 17
    default_pulse_ms: 100
    default_hold_power: 0.375
  c_drop_target_reset:
    file_log: full
    number: 18
    default_pulse_ms: 100
    default_hold_power: 0.375
  c_bumper_1:
    number: 19
  c_bumper_2:
    number: 20
  c_bumper_3:
    number: 21
  c_loop_diverter:
    number: 22
    default_pulse_ms: 100
    default_hold_power: 0.375
  c_scoop_eject:
    number: 23

diverters:
  citadel_diverter:
    activation_coil: c_loop_diverter
    activate_events: activate_citadel_diverter, right_loop_hit
    deactivate_events: deactivate_citadel_diverter
    deactivation_switches: s_conning_tower
    enable_events: enable_citadel_diverter
    disable_events: disable_citadel_diverter
    type: hold
    activation_time: 3s
  torpedo_peg:
    activation_coil: c_torpedo_peg
    activation_switches: s_torpedo
    activate_events: activate_torpedo_peg
    deactivate_events: deactivate_torpedo_peg
    deactivation_switches: s_conning_tower
    enable_events: enable_torpedo_peg
    disable_events: disable_torpedo_peg
    type: hold
    activation_time: 3s
