#config_version=6

slide_player:
  mode_game_started:
    attract:
      action: remove
  single_player_ball_started: score_single
  multiplayer_game:
    score_single:
      action: remove
    score_multi_1:
      action: play
  ball_will_end:
    score_single:
      action: remove
    score_multi_1:
      action: remove
    score_multi_2:
      action: remove
    score_multi_3:
      action: remove
    score_multi_4:
      action: remove
  multi_player_ball_started{current_player.number==1}:
    score_multi_1:
      action: play
  multi_player_ball_started{current_player.number==2}:
    score_multi_2:
      action: play
  multi_player_ball_started{current_player.number==3}:
    score_multi_3:
      action: play
  multi_player_ball_started{current_player.number==4}:
    score_multi_4:
      action: play
  player_turn_ended{number==1}:
    score_multi_1:
      action: remove
  player_turn_ended{number==2}:
    score_multi_2:
      action: remove
  player_turn_ended{number==3}:
    score_multi_3:
      action: remove
  player_turn_ended{number==4}:
    score_multi_4:
      action: remove
  ball_save_main_ball_save_saving_ball:
    ball_saved_slide:
      action: play
      expire: 1s
      priority: 800

show_player:
  flipper_cradle:
    sh_status_report:
      action: play
      priority: 1600
  both_flippers:
    sh_status_report:
      action: advance
  ball_save_main_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_main_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_main_ball_save_disabled:
    ball_save: stop
  ball_save_multiball_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_multiball_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_multiball_ball_save_disabled:
    ball_save: stop
  ball_save_add_a_ball_ball_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_add_a_ball_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_add_a_ball_ball_save_disabled:
    ball_save: stop
  ball_save_dmg_con_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_dmg_con_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_dmg_con_ball_save_disabled:
    ball_save: stop
  ball_save_consumable_multiball_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_consumable_multiball_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: orange
  ball_save_consumable_multiball_ball_save_disabled:
    ball_save: stop

ball_saves:
  main_ball_save:
    active_time: 10s
    balls_to_save: 1
    early_ball_save_events: s_right_outlane_active, s_left_outlane_active
    grace_period: 3s
    hurry_up_time: 3s
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    eject_delay: 1s
    enable_events: ball_started
    disable_events: start_mode_10, add_a_ball, activate_multiball, multiball_consumable_multiball_started
  multiball_ball_save:
    active_time: 10s
    balls_to_save: -1
    early_ball_save_events: s_right_outlane_active, s_left_outlane_active
    grace_period: 3s
    hurry_up_time: 3s
    timer_start_events: ball_save_multiball_ball_save_enabled
    enable_events: activate_multiball
  add_a_ball_ball_save:
    active_time: 10s
    balls_to_save: -1
    early_ball_save_events: s_right_outlane_active, s_left_outlane_active
    grace_period: 3s
    hurry_up_time: 3s
    timer_start_events: ball_save_add_a_ball_ball_save_enabled
    enable_events: add_a_ball
  dmg_con_ball_save:
    active_time: 15s
    balls_to_save: -1
    grace_period: 3s
    hurry_up_time: 3s
    timer_start_events: s_main_hole_inactive
    enable_events: start_mode_10
  consumable_multiball_ball_save:
    active_time: 15s
    balls_to_save: -1
    grace_period: 3s
    hurry_up_time: 3s
    timer_start_events: s_main_hole_inactive
    enable_events: multiball_consumable_multiball_started

