#config_version=5

mode:
    start_events: start_mode_4
    stop_events: end_mode_4
    events_when_started: mode_enabled
    events_when_stopped: mode_disabled
    priority: 300

event_player:
  mglobalcalculate: m4calculate

variable_player:
  m4calculate:
    modetotal: current_player.m4value
    score: current_player.m4value
    m4shotmade: 1
    mode_shot_made:
      int: 1
      action: add
    m4shotremaining:
      int: (4 - current_player.m4shotmade)
      action: set
    modeshotremaining:
      int: (current_player.m4shotremaining)
      action: set
  player_m4entrynumber{current_player.m4entrynumber < 4}:
    entry_modification:
      action: set
      float: (5 - current_player.m4entrynumber) / 4
  player_m4entrynumber{current_player.m4entrynumber >= 4}:
    entry_modification:
      action: set
      float: 1 / 4
  mode_mode_4_started:
    m4entrynumber:
      int: 1
      action: add
    modeentrynumber:
      int: current_player.m4entrynumber
      action: set
    m4value: 
      int: 30000000 * current_player.entry_modification
      action: set
  player_entry_modification:
    m4value: 
      int: 30000000 * current_player.entry_modification
      action: set

show_player:
  m4calculate:
    sh_mode_4_shot_made:
      loops: 0